# after docker compose up -d > localhost:3100/metrics or localhost:3100/ready to see if it is working
# run docker compose up -d --force-recreate to recreate the containers
services:
  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
    networks:
      - loki
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/etc/loki
    networks:
      - loki
  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
    networks:
      - loki
    #logging:
     # driver: loki
      #options:
       # loki-url: "http://loki:3100/loki/api/v1/push"
        #loki-retries: "5"
        #loki-batch-size: "400"
networks:
  loki: {}