server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

# docker logs
# first install docker driver
# run docker plugin ls
# https://grafana.com/docs/loki/latest/send-data/docker-driver/
#scrape_configs:
#  - job_name: docker
#    pipeline_stages:
#      - docker: {}
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: dockerlogs
#          __path__: /var/lib/docker/containers/*/*.log